config/routes.rb
Rails.application.routes.draw do
  root "programs#index"
  resources :programs, only: [:index]
  resources :participants, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant
  include HTTParty

  debug_output $stdout

  base_uri "api.tv4play.se"

  def get_participant(id)
    Rails.cache.fetch("participant/#{id}_cache", expires_in: 1.hour) do
      encoded_person_tag = URI.encode(id.strip)
      response = self.class.get('/play/video_assets.json?tags=' + encoded_person_tag)
      if response.success?
        participant_parsed_hash = response.parsed_response["results"].map do |participant|
          {
            :id => participant["id"],
            :title => participant["title"],
            :description => participant["description"],
            :image => participant["image"],
            :published_date => participant["published_date_time"].to_date,
            :tags => participant["tags"]
          }
        end
      else
        raise response.message
      end
    end
  end

end

app/models/program.rb
class Program
  include HTTParty

  debug_output $stdout

  base_uri "api.tv4play.se"

  def get_program
    Rails.cache.fetch("program_cache", expires_in: 1.hour) do
      response = self.class.get('/site/programs/lets-dance')
      if response.success?
        program_parsed_hash = {
          :nid => response.parsed_response["nid"],
          :name => response.parsed_response["name"],
          :description => response.parsed_response["description"],
          :top_image => response.parsed_response["top_image"],
          :social_block_teasers => response.parsed_response["social_block_teasers"],
          :participants => response.parsed_response["participant_groups"][0]["participants"]
        }
      else
        raise response.message
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController

  def show
    @participant = Participant.new.get_participant(params[:id])
  end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController

  def index
    @program = Program.new.get_program
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Let's Dance</title>
    <%= csrf_meta_tags %>
    <link href="https://cdn.jsdelivr.net/picnicss/6.1.4/picnic.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "partials/header" %>
    <main>
      <%= yield %>
    </main>
    <%= render "partials/footer" %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer>
  <a href="http://www.tv4gruppen.se">© 2016 TV4-Gruppen</a>
</footer>

app/views/partials/_header.html.erb
<header>
  <nav class="primary" itemscope itemtype="http://schema.org/Brand">
    <%= link_to root_path, class: "brand", itemprop: "logo" do %>
      <?xml version="1.0" encoding="utf-8"?>
      <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
      <svg version="1.1" id="Layer_1" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="46.16px" height="46.16px" viewBox="35.02 44.62 46.16 46.16" enable-background="new 35.02 44.62 46.16 46.16" xml:space="preserve">
        <g id="Page-1" sketch:type="MSPage">
          <g id="TV4Play-logotyp-NY" sketch:type="MSLayerGroup">
            <path id="Shape_5_" sketch:type="MSShapeGroup" fill="#FF3334" d="M58.1,90.78c12.76,0,23.08-10.32,23.08-23.08
            c0-12.761-10.319-23.08-23.08-23.08S35.02,54.939,35.02,67.7C35.02,80.42,45.34,90.78,58.1,90.78"/>
            <path id="Shape_6_" sketch:type="MSShapeGroup" fill="#FFFFFF" d="M59.22,75.26h-6l6-8.88V75.26L59.22,75.26z M68.54,75.22h-3.12
            V48.58c0-0.2-0.12-0.4-0.36-0.44c-0.2-0.08-0.4,0-0.52,0.2L42.86,80.38c-0.08,0.16-0.12,0.32-0.04,0.479
            c0.08,0.16,0.24,0.24,0.399,0.24h16V84.7c0,0.239,0.2,0.479,0.48,0.479h5.2c0.279,0,0.479-0.24,0.479-0.479V81.1h3.12
            c0.28,0,0.48-0.199,0.48-0.479V75.7C69.02,75.46,68.82,75.22,68.54,75.22L68.54,75.22z"/>
          </g>
        </g>
      </svg>
      <span>Let's Dance</span>
    <% end %>
    <input id="bmenu" type="checkbox" class="show">
    <label for="bmenu" class="burger toggle pseudo button">menu</label>
    <div class="menu">
      <%= link_to "The program", programs_path, class: "pseudo button" %>
      <%= link_to "Github", "https://github.com/ismailmechbal/letsdance", class: "button" %>
    </div>
  </nav>
</header>

app/views/partials/_navbar.html.erb
<header>
  <nav class="primary" itemscope itemtype="http://schema.org/Brand">
    <%= link_to root_path, class: "brand", itemprop: "logo" do %>
      <?xml version="1.0" encoding="utf-8"?>
      <!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
      <svg version="1.1" id="Layer_1" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="46.16px" height="46.16px" viewBox="35.02 44.62 46.16 46.16" enable-background="new 35.02 44.62 46.16 46.16" xml:space="preserve">
        <g id="Page-1" sketch:type="MSPage">
          <g id="TV4Play-logotyp-NY" sketch:type="MSLayerGroup">
            <path id="Shape_5_" sketch:type="MSShapeGroup" fill="#FF3334" d="M58.1,90.78c12.76,0,23.08-10.32,23.08-23.08
            c0-12.761-10.319-23.08-23.08-23.08S35.02,54.939,35.02,67.7C35.02,80.42,45.34,90.78,58.1,90.78"/>
            <path id="Shape_6_" sketch:type="MSShapeGroup" fill="#FFFFFF" d="M59.22,75.26h-6l6-8.88V75.26L59.22,75.26z M68.54,75.22h-3.12
            V48.58c0-0.2-0.12-0.4-0.36-0.44c-0.2-0.08-0.4,0-0.52,0.2L42.86,80.38c-0.08,0.16-0.12,0.32-0.04,0.479
            c0.08,0.16,0.24,0.24,0.399,0.24h16V84.7c0,0.239,0.2,0.479,0.48,0.479h5.2c0.279,0,0.479-0.24,0.479-0.479V81.1h3.12
            c0.28,0,0.48-0.199,0.48-0.479V75.7C69.02,75.46,68.82,75.22,68.54,75.22L68.54,75.22z"/>
          </g>
        </g>
      </svg>
      <span>Let's Dance</span>
    <% end %>
    <input id="bmenu" type="checkbox" class="show">
    <label for="bmenu" class="burger toggle pseudo button">menu</label>
    <div class="menu">
      <%= link_to "The program", programs_path, class: "pseudo button" %>
      <%= link_to "Github", "https://github.com/picnicss/picnic", class: "button" %>
    </div>
  </nav>
</header>

app/views/participants/_participant_clips.html.erb
<section class="flex one four-500 four-800 participant-clips m-t-b-80">
  <% @participant.each do |participant| %>
    <article class="one" itemscope itemtype="http://schema.org/Clip">
      <%= link_to "http://www.tv4play.se/program/idol?video_id=#{participant[:id]}", itemprop: "url" do %>
        <%= image_tag participant[:image], class: "img-responsive", itemprop: "image" %>
      <% end %>
      <div class="footer">
        <h3 class="title" itemprop="text"><%= link_to participant[:title], "http://www.tv4play.se/program/idol?video_id=#{participant[:id]}" %></h3>
        <h6 itemprop="datePublished" content="<%= participant[:published_date] %>"><%= participant[:published_date] %></h6>
        <% participant[:tags].each do |tag| %>
          <span class="tags" itemprop="keywords"><%= tag %></span>
        <% end %>
      </div>
    </article>
  <% end %>
</section>

app/views/participants/_participant_info.html.erb
<section class="flex participant-info m-t-b-80" itemscope itemtype="http://schema.org/Person" itemprop="actor">
  <h1>Deltagare: <%= params[:id] %></h1>
</section>

app/views/participants/show.html.erb
<%= render "participant_info" %>
<%= render "participant_clips" %>

app/views/programs/_program_intro.html.erb
<section class="flex one program-intro m-t-b-80" itemprop="containsSeason" itemscope itemtype="http://schema.org/TVSeason">
  <h1 itemprop="name"><%= @program[:name] %></h1>
  <p itemprop="headline"><%= @program[:description] %></p>
  <%= image_tag @program[:top_image], alt: @program[:name], itemprop: "image" %>
</section>

app/views/programs/_program_participant.html.erb
<section class="flex one four-500 four-800 program-participant m-t-b-80">
  <% @program[:participants].each do |participant| %>
    <article class="one" itemscope itemtype="http://schema.org/Person" itemprop="actor">
      <%= image_tag participant["image"]["url"], itemprop: "image" %>
      <div class="footer">
        <h2 itemprop="name"><%= link_to participant["name"], participant_path(:id => participant["person_tag"]), itemprop: "url" %></h2>
        <p class="description" itemprop="description"><%= participant["description"] %></p>
      </div>
    </article>
  <% end %>
</section>

app/views/programs/_program_teasers.html.erb
<section class="program-teasers m-t-b-80">
  <% @program[:social_block_teasers].each do |item| %>
    <article class="flex one three-500 three-800" itemscope itemtype="http://schema.org/Article">
      <div class="one">
        <%= link_to item["link_url"], itemprop: "url" do %>
          <%= image_tag item["image"], class: "img-responsive", itemprop: "image" %>
        <% end %>
      </div>
      <div class="one">
        <h2 itemprop="name"><%= item["heading"] %></h2>
        <p itemprop="about"><%= item["lead"] %></p>
        <%= link_to item["kicker"], item["link_url"], itemprop: "url" %>
      </div>
    </article>
  <% end %>
</section>

app/views/programs/index.html.erb
<%= render "program_intro" %>
<%= render "program_teasers" %>
<%= render "program_participant" %>